groups:
  - name: default
    rules:
      - alert: node_down
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: “node_down (instance {{ $labels.instance }})”